version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: currency_converter_app
    ports:
      - "8000:80"
    volumes:
      - ./:/srv/app:delegated
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: currency_converter
      DB_USERNAME: app
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: currency_converter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_converter
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: currency_converter_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "9080:80"

volumes:
  dbdata:

networks:
  default:
    driver: bridge
